Create the client README file
andela/knights-bn-frontend pull request #2
Opened 2020-04-15 14:18 UTC by Niyonsengaeric

#### What does this PR do?
 This PR ensures that the README file has all the information required to help a user to use the system.
#### Description of Task to be completed?
- Create a README file to help a user to interact with the system.

#### How should this be manually tested?
- Go to the [https://github.com/andela/knights-bn-frontend.git)

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#170947601](https://www.pivotaltracker.com/story/show/170947601)

#### Screenshots
N/A

2020-04-15 16:15 UTC, Kagorora reviewed
@Niyonsengaeric  can you try to give as many details as you can, search as :

1. Tools that you need to use this app.
2. The link of the backend
3. Description of the project
4. Name of the contributors

and other materials that needs to be included

2020-04-16 06:49 UTC, EugeneMunya approved these changes

2020-04-16 07:00 UTC, Kagorora approved these changes

2020-04-16 07:05 UTC, T2Wil commented
Hey @Niyonsengaeric , 
consider changing the commit message footer from `start` to `finishes`

2020-04-16 07:33 UTC, T2Wil approved these changes

2020-04-16 13:40 UTC, kagabof requested changes

2020-04-16 13:40 UTC, kagabof commented on README.md
> + ### TTL
Please Put TTL in full.

2020-04-16 14:22 UTC, kagabof commented
Well done.

2020-04-16 14:22 UTC, kagabof approved these changes

2020-04-16 14:22 UTC, merged